# Generated by Django 4.2 on 2023-04-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
